service: alexa-afl

provider:
  name: aws
  runtime: go1.x

stage: dev
region: ap-southeast-2

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  win_next:
    handler: bin/win_next
  win_premiership:
    handler: bin/win_premiership
