service: alexa-afl

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  win_next:
    handler: bin/win_next
    events:
      - alexaSkill:
        appId: amzn1.ask.skill.f6128da6-7813-4025-a762-b78be8fc6863
